HEAD:
  mixed-port: 7890
  allow-lan: true
  mode: rule
  log-level: info
  external-controller: :9090
  dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query', 'tls://8.8.4.4:853']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
TEST_URL: https://www.gstatic.com/generate_204
RULESET:
- - ChatBot
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Ruleset/OpenAi.list
- - ChatBot
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Ruleset/ChatBot.list
- - å…¨çƒç›´è¿
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/LocalAreaNetwork.list
- - å…¨çƒç›´è¿
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/UnBan.list
- - å¹¿å‘Šæ‹¦æˆª
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/BanAD.list
- - åº”ç”¨å‡€åŒ–
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/BanProgramAD.list
- - å¹¿å‘Šæ‹¦æˆª
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/BanEasyList.list
- - å¹¿å‘Šæ‹¦æˆª
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/BanEasyListChina.list
- - éšç§é˜²æŠ¤
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/BanEasyPrivacy.list
- - è°·æ­ŒFCM
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Ruleset/GoogleFCM.list
- - è°·æ­ŒæœåŠ¡
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Ruleset/Google.list
- - å…¨çƒç›´è¿
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Ruleset/Adobe.list
- - å¾®è½¯Bing
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Bing.list
- - å¾®è½¯äº‘ç›˜
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/OneDrive.list
- - å¾®è½¯æœåŠ¡
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Microsoft.list
- - Telegram
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Telegram.list
- - Telegram
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Tailscale.list
- - æµ·å¤–æ¸¸æˆ
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Ruleset/Epic.list
- - æµ·å¤–æ¸¸æˆ
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Ruleset/Origin.list
- - æµ·å¤–æ¸¸æˆ
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Ruleset/Sony.list
- - æµ·å¤–æ¸¸æˆ
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Ruleset/Steam.list
- - æµ·å¤–æ¸¸æˆ
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Ruleset/Nintendo.list
- - é˜¿é‡Œäº‘éªŒè¯ç 
  - 'DOMAIN(cf.aliyun.com)'
- - YouTube
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/Ruleset/YouTube.list
- - å›½å†…åª’ä½“
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/ChinaMedia.list
- - å›½å¤–åª’ä½“
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/ProxyMedia.list
- - èŠ‚ç‚¹é€‰æ‹©
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/ProxyGFWlist.list
- - å…¨çƒç›´è¿
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/ChinaIp.list
- - å…¨çƒç›´è¿
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/ChinaDomain.list
- - å…¨çƒç›´è¿
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/ChinaCompanyIp.list
- - å…¨çƒç›´è¿
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/HighSpeedCDN.list
- - å…¨çƒç›´è¿
  - https://raw.githubusercontent.com/Sunakier/WQ-Rule-From-ZJU/main/Clash/PriviteDirectIP.list
- - å…¨çƒç›´è¿
  - '[]GEOIP,CN'
- - æ¼ç½‘ä¹‹é±¼
  - '[]FINAL'
CUSTOM_PROXY_GROUP:
- name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  rule: false
- name: æ‰‹åŠ¨åˆ‡æ¢1
  type: select
  manual: true
  rule: false
- name: æ‰‹åŠ¨åˆ‡æ¢2
  type: select
  manual: true
  rule: false
- name: æ•…éšœè½¬ç§»
  type: fallback
  rule: false
- name: è´Ÿè½½å‡è¡¡
  type: load-balance
  rule: false
- name: é¦™æ¸¯è´Ÿè½½å‡è¡¡
  type: load-balance
  rule: false
  regex: ğŸ‡­ğŸ‡°|HK|Hong|Kong|HGC|WTT|CMI|æ¸¯
- name: ChatBot
  type: select
  prior: PROXY
- name: Telegram
  type: select
  prior: PROXY
- name: Tailscale
  type: select
  prior: DIRECT
- name: YouTube
  type: select
  prior: PROXY
- name: å›½å¤–åª’ä½“
  type: select
  prior: PROXY
- name: å›½å†…åª’ä½“
  type: select
  prior: DIRECT
- name: è°·æ­ŒFCM
  type: select
  prior: DIRECT
- name: è°·æ­ŒæœåŠ¡
  type: select
  prior: PROXY
- name: å¾®è½¯Bing
  type: select
  prior: PROXY
- name: å¾®è½¯äº‘ç›˜
  type: select
  prior: DIRECT
- name: å¾®è½¯æœåŠ¡
  type: select
  prior: DIRECT
- name: è‹¹æœæœåŠ¡
  type: select
  prior: DIRECT
- name: æµ·å¤–æ¸¸æˆ
  type: select
  prior: DIRECT
- name: å…¨çƒç›´è¿
  type: select
  prior: DIRECT
- name: é˜¿é‡Œäº‘éªŒè¯ç 
  type: select
  prior: DIRECT
- name: å¹¿å‘Šæ‹¦æˆª
  type: select
  prior: REJECT
- name: åº”ç”¨å‡€åŒ–
  type: select
  prior: REJECT
- name: éšç§é˜²æŠ¤
  type: select
  prior: REJECT
- name: æ¼ç½‘ä¹‹é±¼
  type: select
  prior: PROXY
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡­ğŸ‡°|HK|Hong|Kong|HGC|WTT|CMI|æ¸¯
- name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡¹ğŸ‡¼|TW|Taiwan|æ–°åŒ—|å½°åŒ–|CHT|å°|HINET
- name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡¸ğŸ‡¬|SG|Singapore|ç‹®åŸ|^æ–°[^èŠ‚åŒ—]|[^åˆ·æ›´]æ–°[^èŠ‚åŒ—]
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡¯ğŸ‡µ|JP|Japan|Tokyo|Osaka|Saitama|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|æ—¥
- name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡°ğŸ‡·|KO?R|Korea|é¦–å°”|éŸ©|éŸ“
- name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡ºğŸ‡¸|US|America|United.*?States|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥
